import { TravelForm, User } from '@/types/travel-form';

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    username: 'john.doe',
    password: 'pass123',
    name: 'John Doe',
    role: 'submitter',
    department: 'Operations',
  },
  {
    id: 'u2',
    username: 'jane.smith',
    password: 'pass123',
    name: 'Jane Smith',
    role: 'submitter',
    department: 'Marketing',
  },
  {
    id: 'u3',
    username: 'sarah.mgr',
    password: 'pass123',
    name: 'Sarah Johnson',
    role: 'finance_approver',
    department: 'Finance',
  },
  {
    id: 'u4',
    username: 'admin.final',
    password: 'pass123',
    name: 'Michael Peters',
    role: 'final_approver',
    department: 'Executive',
  },
];

export const SEED_FORMS: TravelForm[] = [
  {
    id: 'f1',
    tripNo: 'TRIP-2026-001',
    applicantId: 'u1',
    applicantName: 'John Doe',
    travelFromDate: '2026-05-10',
    travelToDate: '2026-05-12',
    purpose: 'Facilities Management Strategy Session',
    costCode: 'FM-2026-CC01',
    flights: [
      {
        id: 'fl1',
        date: '2026-05-10',
        from: 'JHB',
        to: 'CPT',
        departureTime: '07:00',
        arrivalTime: '09:15',
        flightNo: 'FA101',
        priorityPass: false,
        windowSeat: true,
      },
    ],
    hotels: [
      {
        id: 'h1',
        dateIn: '2026-05-10',
        dateOut: '2026-05-12',
        location: 'Cape Town',
        hotelName: 'The Table Bay Hotel',
        boardBasis: 'B&B',
        estimatedCost: '3500',
      },
    ],
    carHires: [],
    shuttles: [
      {
        id: 's1',
        pickupDate: '2026-05-10',
        shuttleCompany: 'Cape Shuttle Co.',
        pickupAddress: 'CPT Airport',
        dropoffAddress: 'The Table Bay Hotel, V&A Waterfront',
        mobileNumber: '0821234567',
      },
    ],
    dailyAllowances: {
      international: { nightsAway: '', amount: '' },
      local: { nightsAway: 2, stAmount: 750 },
    },
    status: 'Pending',
    approvals: [],
    createdAt: '2026-05-08T08:00:00.000Z',
    updatedAt: '2026-05-08T08:30:00.000Z',
  },
  {
    id: 'f2',
    tripNo: 'TRIP-2026-002',
    applicantId: 'u2',
    applicantName: 'Jane Smith',
    travelFromDate: '2026-05-15',
    travelToDate: '2026-05-17',
    purpose: 'Marketing Conference - Durban',
    costCode: 'MKT-2026-CC03',
    flights: [
      {
        id: 'fl2',
        date: '2026-05-15',
        from: 'JHB',
        to: 'DUR',
        departureTime: '06:30',
        arrivalTime: '08:00',
        flightNo: 'FA205',
        priorityPass: true,
        windowSeat: false,
      },
    ],
    hotels: [
      {
        id: 'h2',
        dateIn: '2026-05-15',
        dateOut: '2026-05-17',
        location: 'Durban',
        hotelName: 'Hilton Durban',
        boardBasis: 'Room Only',
        estimatedCost: '2800',
      },
    ],
    carHires: [
      {
        id: 'c1',
        pickupDate: '2026-05-15',
        dropoffDate: '2026-05-17',
        location: 'Durban',
      },
    ],
    shuttles: [],
    dailyAllowances: {
      international: { nightsAway: '', amount: '' },
      local: { nightsAway: 2, stAmount: 750 },
    },
    status: 'FinanceApproved',
    approvals: [
      {
        approverName: 'Sarah Johnson',
        approverId: 'u3',
        date: '2026-05-08T10:00:00.000Z',
        stage: 'finance',
      },
    ],
    createdAt: '2026-05-07T09:00:00.000Z',
    updatedAt: '2026-05-08T10:00:00.000Z',
  },
  {
    id: 'f3',
    tripNo: 'TRIP-2026-003',
    applicantId: 'u1',
    applicantName: 'John Doe',
    travelFromDate: '2026-06-01',
    travelToDate: '2026-06-05',
    purpose: 'International Partner Meeting - London',
    costCode: 'OPS-2026-CC07',
    flights: [
      {
        id: 'fl3',
        date: '2026-06-01',
        from: 'JHB',
        to: 'LHR',
        departureTime: '20:00',
        arrivalTime: '06:30',
        flightNo: 'BA056',
        priorityPass: true,
        windowSeat: false,
      },
    ],
    hotels: [
      {
        id: 'h3',
        dateIn: '2026-06-02',
        dateOut: '2026-06-05',
        location: 'London',
        hotelName: 'Premier Inn London',
        boardBasis: 'B&B',
        estimatedCost: '12000',
      },
    ],
    carHires: [],
    shuttles: [],
    dailyAllowances: {
      international: { nightsAway: 3, amount: 2500 },
      local: { nightsAway: '', stAmount: '' },
    },
    status: 'Draft',
    approvals: [],
    createdAt: '2026-05-08T11:00:00.000Z',
    updatedAt: '2026-05-08T11:00:00.000Z',
  },
];
